easy_admin:
    entities:
        Contact:
            class: App\Entity\Contact
            controller: App\Controller\Admin\ContactCrudController
        Blog:
            class: App\Entity\Blog
            list:
                actions:
                    - ['index', 'app_blog']
                fields:
                    - title
                    - content
                    - image
