easy_admin:
    entities:
        Contact:
            class: App\Entity\Contact
            controller: App\Controller\Admin\ContactCrudController
        Blog:
            class: App\Entity\Blog
            list:
                actions:
                    - ['index', 'app_blog']
                fields:
                    - title
                    - content
                    - image
                    - category
            form:
                fields:
                    - image
                    - title
                    - content
                    - category
            edit:
                fields:
                    - id
                    - image
                    - title
                    - content
                    - category
        Galerie:
            class: App\Entity\Galerie
            list:
                actions:
                    - { name: 'listeNomsPrenoms', label: 'Liste Noms et Prénoms' }        